<?php

// Language definitions used in Backup plugin
$lang_admin_plugin_backup = array(
	'Header line'			=> '-- SQL dump commenced %s'."\n".'-- Generated by FluxBB Backup Plugin'."\n".'-- Dumping database: %s'."\n".'-- Database type: %s'."\n",
	'Unknown database'		=> 'Your database is currently not supported.',
	'Table data for'		=> 'Table data for %s',
	'Table structure for'	=> 'Table structure for %s',
	'No directory'			=> 'You didn\'t specify a directory to save to.',
	'Unable to write'		=> 'Unable to write to the specified directory, please make sure it exists and is writable by PHP.',
	'Backup Successful'		=> 'Backup Successful!',
	'Backup written'		=> 'A backup has successfully been written to the local filesystem at: %s',
);
