<?php

// Language definitions used in Backup plugin
$lang_admin_plugin_backup = array(
	'Header line'			=> '-- SQL dump commenced at %s'."\n".'-- Generated by FluxBB Backup Plugin'."\n".'-- Dumping database %s'."\n".'-- Database type: %s'."\n",
	'Unknown database'		=> 'Your database is currently not supported.',
);
